In [2]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [4]:
y = (np.ones((1, 20))) * 2
z = np.arange(1, 21, 1)
(y ** z) / z

array([[  2.00000000e+00,   2.00000000e+00,   2.66666667e+00,
          4.00000000e+00,   6.40000000e+00,   1.06666667e+01,
          1.82857143e+01,   3.20000000e+01,   5.68888889e+01,
          1.02400000e+02,   1.86181818e+02,   3.41333333e+02,
          6.30153846e+02,   1.17028571e+03,   2.18453333e+03,
          4.09600000e+03,   7.71011765e+03,   1.45635556e+04,
          2.75941053e+04,   5.24288000e+04]])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [5]:
x = (np.ones((1, 6))) * 0.1
y = (np.ones((1, 6))) * 0.2
i = np.arange(0, 6, 1)
x = x ** (3 * i)
y = np.transpose(y ** (4 * i))
np.dot(x, y)

array([[ 1.0000016]])

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [7]:
a = np.zeros((8, 8))
a[1::2,  1::2] = 1
a[::2,  ::2] = 1
a

array([[ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [8]:
X = np.random.random((5, 2))
q = (((X[:, 0]) ** 2) + (X[:, 1]) ** 2) ** (1 / 2)
y = np.arctan((X[:, 1]) / X[:, 0])
(np.array([q, y])).T

array([[ 0.70356371,  1.08951362],
       [ 0.98469432,  0.98599814],
       [ 0.85112117,  0.57897556],
       [ 1.25411015,  0.78330962],
       [ 1.3510463 ,  0.7992225 ]])

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [13]:
X = np.random.random((10, 10))
print(X, "\nIndexes: ", np.array([X.argmax() // 10, X.argmax() % 10]))

[[ 0.56788501  0.86957105  0.00766546  0.54062969  0.13988869  0.05445318
   0.86602043  0.39832871  0.00601944  0.61633179]
 [ 0.38127697  0.58783904  0.36874176  0.44361017  0.00134983  0.50262802
   0.65402455  0.39680736  0.76563294  0.54819634]
 [ 0.415174    0.63380525  0.2929979   0.3068743   0.22274286  0.62325416
   0.35813531  0.98457141  0.38088279  0.84654394]
 [ 0.83911016  0.65153454  0.48677325  0.64545993  0.49315002  0.83468593
   0.98180355  0.89795961  0.95971322  0.77099357]
 [ 0.52648024  0.06892401  0.83055356  0.58486064  0.35102284  0.51890394
   0.71947216  0.76432902  0.83382503  0.00778337]
 [ 0.94117893  0.10242033  0.7833075   0.46957583  0.46999612  0.66598995
   0.86415635  0.26627471  0.83445071  0.1510713 ]
 [ 0.15114999  0.31461326  0.89122022  0.82817689  0.71061279  0.14543387
   0.46585356  0.49010256  0.7460152   0.28869594]
 [ 0.16438123  0.95239075  0.66342566  0.22192241  0.62507325  0.42725936
   0.76345711  0.4494641   0.57831838  0.93558281]


**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [15]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))
z = X - y
print(X, '\n\n', y, '\n\n', np.argmin(abs(((z[:, 0])**2+(z[:, 1])**2)**(1/2))))

[[ 0.21933369  0.95363601]
 [ 0.31246722  0.10723887]
 [ 0.9133007   0.97994446]
 [ 0.30674291  0.72159463]
 [ 0.95227795  0.05723349]
 [ 0.75932485  0.84603113]
 [ 0.04131256  0.98676172]
 [ 0.11406616  0.0158279 ]
 [ 0.35441469  0.17547053]
 [ 0.65627144  0.60732543]] 

 [[ 0.14504257  0.64064371]] 

 3


**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [16]:
x = np.arange(-3, 4, 1)
y = np.array([*(((x[:3]) ** 2) + 2 * (x[:3]) + 6), *(x[3:5] + 6), *((x[5:]) ** 2 + 4 * (x[5:]) - 4)])
y

array([ 9,  6,  5,  6,  7,  8, 17])

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [13]:
X = np.random.random((10, 10))
A = (np.ones((10, 10)) * (X.mean(axis = 1))).T
R = X - A
print(X, '\n\n', R, '\n\n', np.around(R.sum(axis = 1), decimals = 10))

[[ 0.69756548  0.75540878  0.86323436  0.19622091  0.89210646  0.26741415
   0.43302144  0.75827878  0.18945175  0.25613055]
 [ 0.54386424  0.7534738   0.06556096  0.35613101  0.1974261   0.71345417
   0.65053572  0.30068547  0.85008151  0.16671249]
 [ 0.58479336  0.54732054  0.28221969  0.13384489  0.92689102  0.04659597
   0.68856799  0.23158831  0.30732582  0.02470442]
 [ 0.29441116  0.66368859  0.22412278  0.48949288  0.0918173   0.42129841
   0.21161304  0.27241577  0.0809564   0.40308335]
 [ 0.45035924  0.19735027  0.02606642  0.53401516  0.49464125  0.80022751
   0.45374357  0.8855406   0.51040204  0.19637357]
 [ 0.71609532  0.41313314  0.03375659  0.65226649  0.91927611  0.81462087
   0.6434096   0.29099993  0.22716057  0.92911302]
 [ 0.70637601  0.67747768  0.50119669  0.46649466  0.37863423  0.25245008
   0.7001912   0.77531363  0.15623249  0.48853589]
 [ 0.28319059  0.19643943  0.80656318  0.06900202  0.7738957   0.71264562
   0.1695373   0.44412677  0.32808845  0.87924363]


**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [14]:
X = np.random.normal(loc=5, scale=2., size=1000)
A = X.mean()
S = (((X - A) ** 2).mean())
print('Mean: ', A, '\nVariance: ', S)

Mean:  4.9687938841 
Variance:  4.08719562939


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [15]:
(((np.arange(0, 36)) % 5).reshape(6, 6))[:5, :5]

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]], dtype=int32)